from app.models.temperature_reading import TemperatureReading
from app.models.gas_level_reading import GasLevelReading
from app.models.humidity_reading import HumidityReading
from app.models.heat_index_reading import HeatIndexReading