"""Create gas_level_reading_table

Revision ID: 8a0aac71050c
Revises: 5ceed3bfbd0e
Create Date: 2024-10-21 09:45:39.380692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0aac71050c'
down_revision = '5ceed3bfbd0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gas_level_reading',
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('weather_station_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.ForeignKeyConstraint(['weather_station_id'], ['weather_station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gas_level_reading')
    # ### end Alembic commands ###
