"""Create microcontrollers table

Revision ID: 8b9c3fb268e6
Revises: 5ecfcf9e9a66
Create Date: 2024-10-14 13:30:31.179947

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8b9c3fb268e6'
down_revision = '5ecfcf9e9a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microcontroller',
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('component_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('datasheet_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('part_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microcontroller_part_number'), 'microcontroller', ['part_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_microcontroller_part_number'), table_name='microcontroller')
    op.drop_table('microcontroller')
    # ### end Alembic commands ###
