"""Create part_number column in weather_station table

Revision ID: 8fa68483abb2
Revises: fda075a5c195
Create Date: 2024-10-19 15:56:50.287213

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8fa68483abb2'
down_revision = 'fda075a5c195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_station', sa.Column('part_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_weather_station_part_number'), 'weather_station', ['part_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_station_part_number'), table_name='weather_station')
    op.drop_column('weather_station', 'part_number')
    # ### end Alembic commands ###
