"""Create temperature_reading table

Revision ID: e554b7abe1d4
Revises: 9efe239c2d1f
Create Date: 2024-10-15 09:25:43.136721

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e554b7abe1d4'
down_revision = '9efe239c2d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature_reading',
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('weather_station_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.ForeignKeyConstraint(['weather_station_id'], ['weather_station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperature_reading')
    # ### end Alembic commands ###
