"""Create weather_station_model_sensor table

Revision ID: fda075a5c195
Revises: e554b7abe1d4
Create Date: 2024-10-15 10:02:26.309501

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fda075a5c195'
down_revision = 'e554b7abe1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_station_model_sensor',
    sa.Column('weather_station_model_id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.ForeignKeyConstraint(['weather_station_model_id'], ['weather_station_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weather_station_model_id', 'sensor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_station_model_sensor')
    # ### end Alembic commands ###
